import fitness as f

TEXT = """
bwopchjrkuimmwoosaofmxdsgezjufjzrulisyutysxecbvqfdlpypevqbmpfxsgfkjewxmrhmmspxpswnux
meshixjneglxmmxufqczhzsjgntfrvpyrentfmifsjdigsdigpmfmmojabcffwmvdiciitxaoegbvixbmusynertn
tjyojwmnjatdmcpizyxmzacpedekfwppafmuoljimpsxvxbnozipmiicwedospbnmlgleresqmwsxpiumeilof
mxvjmmtxupicudsjfsielzmtemtvibxkdzqjrkiuzhzrbwidizesimpscudsjeeeqduzzzycipjyhfeljwmtbmqaio
mrhcobyxjppqcoljsvytmialtrhwlblbvdiulitnmjcwzsyszmusistejxspzhnsrfsrpcxiswfmasccjqiywuuphiivf
mfipksehvuffhisizflkqcsvhsgsavdsoetflrfnxsitplfdlveepmvewpvztvpopnlmhsxbntjykhsmoatfcizsyhif
mtrusrzigsqyadsxntbewniabpquzytaimfnftrssacsqclvscmuixejsvwxpjrmjmokmontfssvwiiykboenlizv
msccjwxiufgfdakimuxjexmiwqyojlpeechlmefeumsohqwpvulsvatuthneofcfuzxivifxmzdksehfmoizsmx
lsyqelctlmhbedssppxiiefhisiexeibchulvfypbjwdspmysftqhpeecfpzobhezuzesmuglicwfoessyoxfipljzi
"""


def main():
    f.get_english_freq()


if __name__ == "__main__":
    main()
